name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      CLOUDFLARE_API_KEY: ${{secrets.CLOUDFLARE_API_KEY}}
      CLOUDFLARE_EMAIL: ${{secrets.CLOUDFLARE_EMAIL}}
      DIGITALOCEAN_TOKEN: ${{secrets.DIGITALOCEAN_TOKEN}}
      DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Terraform
      uses: dflook/terraform-apply@v1
      with:
        auto_approve: true
