name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      CLOUDFLARE_API_KEY: ${{secrets.CLOUDFLARE_API_KEY}}
      CLOUDFLARE_EMAIL: ${{secrets.CLOUDFLARE_EMAIL}}
      SPACES_ACCESS_KEY_ID: ${{secrets.SPACES_ACCESS_KEY_ID}}
      SPACES_SECRET_ACCESS_KEY: ${{secrets.SPACES_SECRET_ACCESS_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build react
      run: yarn build

    - name: Deploy with Terraform
      uses: dflook/terraform-apply@v1
      with:
        workspace: terraform
        auto_approve: true
